# Generated by Django 4.0.5 on 2022-07-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_display_full', models.CharField(max_length=64)),
                ('MLB_API_ID', models.CharField(max_length=8)),
                ('division', models.CharField(max_length=16)),
                ('name_abbrev', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTwitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=64)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_handle', to='baseball.teams')),
            ],
        ),
    ]
