# Generated by Django 4.0.5 on 2022-07-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_favoriteteams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteteams',
            old_name='team',
            new_name='team_name',
        ),
    ]
