# Generated by Django 4.0.5 on 2022-07-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_favoriteplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteplayers',
            name='player_position',
            field=models.CharField(default='P', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteplayers',
            name='player_team_abbrev',
            field=models.CharField(default='LAA', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteplayers',
            name='player_team_full',
            field=models.CharField(default='Colorado Rockies', max_length=64),
            preserve_default=False,
        ),
    ]
